### ISSUE TITLE
Get the coordinates and size of sprites that are inside atlas

### ISSUE THREAD

**Issue by aneopsy** [nesrak1/AssetsTools.NET#11]
Is not an issue but do you know how to get the _coordinates_ and _size_ of sprites that are inside **atlas** ?

I'm trying to build and unpacker for atlas.

**Comment by nesrak1** [comment]
Here was code I used in the old hkwe edit that turned sprites into texture2d's. It's a bit redundant in some places but it works: https://github.com/nesrak1/HKWorldEdit/blob/master/Assets/Editor/SpriteLoader.cs

**Comment by aneopsy** [comment]
Uhm let me explain,
for exemple, the spritesheet of **hollow knight** (the character) for the animation is [atlas0-1992174.png](https://image.noelshack.com/fichiers/2019/41/7/1570928960-atlas0-1992174.png) and I would like to unpack this _atlas_ to multiple _sprite_.
I would like to know where to get the coordinates of each sprite to split the _atlas_?

For more information:
When I open the level4, I have a _gameobject_ called _knight_ with a mesh render and a material of the knight [screenshoot](https://image.noelshack.com/fichiers/2019/41/7/1570929623-capture.png) but there is no way to display an image of the knight

**Comment by nesrak1** [comment]
These sprites are saved in tk2d data, not unity sprite renderers, which is in the same file above in `LoadTK2dSprite`, choose a spriteid to get different sprites. croppedBitmap variable is the coordinates of the sprite. If you want to get this working in the editor, its a little different, especially if you want to get it working in the bundle instead of at load time.

**Comment by aneopsy** [comment]
Thank you for these information
