### ISSUE TITLE
Modifying AssetBundles

### ISSUE THREAD

**Issue by remixer-dec** [nesrak1/AssetsTools.NET#17]
Greetings. Is there a way to replace file in assets inside assetBundle, and save the modified bundle?
I got the decompression and extraction part with AssetView.NET code, but replacement seems to be not clear... 
After using the sample code from readme for modification (even without the part that modifies filename), the exported output file seems to be filled with [Unicode replacement character](https://apps.timwhitlock.info/unicode/inspect?s=%EF%BF%BD), same thing happened when I tried to extract TextAsset using baseField.Get("m_Script").GetValue().AsString() (and not only as string). 
My goal is to modify TextAsset data and save modified asset bundle. 

And even if i'll manage to get a modified asset, how can I place it as a replacement in asset bundle and then save it?  
This code always creates an empty 2KB bundle, even if original bundle is not empty
```C#
var am = new AssetsManager();
var ab = am.LoadBundleFile(FilePath);
var writer = new AssetsFileWriter(File.OpenWrite("output.ab"));
ab.file.Write(writer);

```

P.S. I would like to notice that the [sample code](https://github.com/nesrak1/AssetsTools.NET#assets-file-writing) has multiple errors in it (variable is used before declaration, curFileType is not converted to int, Write function uses AssetsReplacer array instead of List, and is missing two other arguments [required ](https://github.com/nesrak1/AssetsTools.NET/blob/60ba6907ec6c356aa28bf62a35b3a2fb116c7a64/AssetTools.NET/Standard/AssetsFileFormat/AssetsFile.cs#L61)by the function) which is really confusing...

**Comment by nesrak1** [comment]
> Greetings. Is there a way to replace file in assets inside assetBundle, and save the modified bundle?
> I got the decompression and extraction part with AssetView.NET code, but replacement seems to be not clear...

Bundles are something that I sort of forgot about and haven't used too much, so there hasn't been much testing on them.

> After using the sample code from readme for modification (even without the part that modifies filename), the exported output file seems to be filled with [Unicode replacement character](https://apps.timwhitlock.info/unicode/inspect?s=%EF%BF%BD), same thing happened when I tried to extract TextAsset using baseField.Get("m_Script").GetValue().AsString() (and not only as string).
> My goal is to modify TextAsset data and save modified asset bundle.

I think this might be a problem with the header (or the whole bundle) being compressed and not getting unpacked with the code from AssetsManager. Will add on the todo list of things to fix.

> 
> And even if i'll manage to get a modified asset, how can I place it as a replacement in asset bundle and then save it?
> This code always creates an empty 2KB bundle, even if original bundle is not empty
> 
> ```cs
> var am = new AssetsManager();
> var ab = am.LoadBundleFile(FilePath);
> var writer = new AssetsFileWriter(File.OpenWrite("output.ab"));
> ab.file.Write(writer);
> ```

I'm not actually sure what happened to the bundle write code. I think before there was bundle write support you could manually write the headers and then write the assets files' data immediately after. Anyway, it's now on the todo list for things to fix.

> P.S. I would like to notice that the [sample code](https://github.com/nesrak1/AssetsTools.NET#assets-file-writing) has multiple errors in it (variable is used before declaration, curFileType is not converted to int, Write function uses AssetsReplacer array instead of List, and is missing two other arguments [required ](https://github.com/nesrak1/AssetsTools.NET/blob/60ba6907ec6c356aa28bf62a35b3a2fb116c7a64/AssetTools.NET/Standard/AssetsFileFormat/AssetsFile.cs#L61)by the function) which is really confusing...

Thanks for the notice on the sample code, it was pretty old and I changed some things in the example I intended to change in the library and vice versa which is why it's as broken as it is.

Anyway, I'll make some commits and ping you when it seems like it's working again. Sorry again about the issues, it's just a part of the lib I don't use too often.

**Comment by nesrak1** [comment]
Sorry about the long wait. I was pretty busy this past week and then had a little trouble implementing bundle write support. There are still some things I'm not sure about (like what Init method or hasSerializedData field do) but I ran a few tests (see project below) and it seems to create valid bundles. I haven't done much testing though, I'm sure there's still some bugs that need to be worked out so I wouldn't be surprised if some files / modes crash right now.

[AssetsToolsBundleTest.zip](https://github.com/nesrak1/AssetsTools.NET/files/4881883/AssetsToolsBundleTest.zip)

**Comment by remixer-dec** [comment]
Thanks for such a quick response and implementation! I tried out your test files, and it seems to work partially with some bundles, and in this case, other tools manage to open them. However, I had 0 success with modified bundles in game. The game either crashes with "out of memory" error or outputs an error about wrong target version (I'm not sure if this is due to a library bug or my weird asset replacement way, described in the end). I did the same thing with the same bundle manually, using UABE, and it worked perfectly fine.  
  
For example, using this code on [this](https://yadi.sk/d/-ElJROrEFVNCJQ) bundle:
```C#
var am = new AssetsManager();
am.LoadClassPackage("classdata.tpk"); //idk if I even need this line
var ab = am.LoadBundleFile(FilePath); 
var bwriter = new AssetsFileWriter(File.OpenWrite("output.ab"));
ab.file.Write(bwriter, new List<BundleReplacer> {  });
```
with no modifications or replacements, outputs corrupt bundle, which leads to out of memory error.  
  
Since my target game is using TextAssets to store encrypted AssetBundles in them, I was also looking for a way to put a byteArray as baseField value without any encoding-based operations, here is my solution, may be there is an easier way...
```C#
int headerLength = (int)(Math.Ceiling((double)(targetResourceName.Length + 4) / 4) * 4);
byte[] header = baseField.WriteToByteArray().Take(headerLength).ToArray();
byte[] fileLength = BitConverter.GetBytes((uint)byteArrayWithFile.Length);
byte[] fileLength4B = fileLength.Concat(new Byte[4 - fileLength.Length]).ToArray();
byte[] output = header.Concat(fileLength4B).Concat(byteArrayWithFile).ToArray();
var fileReplacer = new AssetsReplacerFromMemory(0, assetInfo.index, 0x31, 0xFFFF, output);
```

**Comment by nesrak1** [comment]
I'll look into the loading problems but I thought I tested for exact bytes when writing...
> Since my target game is using TextAssets to store encrypted AssetBundles in them, I was also looking for a way to put a byteArray as baseField value without any encoding-based operations, here is my solution, may be there is an easier way...

So usually you would use a BinaryWriter instead of manually doing operations on byte arrays.
```cs
byte[] asset;
using (var ms = new MemoryStream())
using (var writer = new AssetsFileWriter(ms))
{
    writer.WriteCountStringInt32(targetResourceName);
    writer.Align();
    writer.Write((int)byteArrayWithFile.Length);
    writer.Write(byteArrayWithFile);
    asset = ms.ToArray();
}
var fileReplacer = new AssetsReplacerFromMemory(0, assetInfo.index, 0x31, 0xFFFF, asset);
```

I realize it's still complicated and requires knowing how the asset format works. Something that I want to plan on adding is the ability to create an empty asset, similar to the "try to create valid asset" thing in UABE (this is unique to UABE and not part of the AssetsTools library as far as I know.)

**Comment by rashime** [comment]
I had the same problem modifying asset bundles (bundles are rewritten and can be edited with tools like UABE, but the game fails to load them).

While comparing a file modified with UABE and the library I noticed the AssetsFileHeader metadata size in the file produced by UABE was 1 byte larger (there was also some extra data at the end of the bundle produced by the library but did not seem to cause issues).  When I added 1 to the metadata size (where it was writing in AssetsFile.cs:249), the bundle that was being saved is read properly by the game, at least in my initial testing.

I don’t know enough about the file structure to know why it would be a byte off or if it is something specific to the bundle I am currently trying to modify, but figured I would mention it in case it is helpful in tracking down the problem.

**Comment by nesrak1** [comment]
@remixer-dec I forgot about the 0x80 flag that bundles have that move the info to the back of the asset instead of the front. Now when you write, it unsets the flag but in the future I'll try to keep the file in as close to the same format as possible.
@rashime Seems more like an assets file problem than a bundle problem. Anyway, a while ago I added one to the GetSizeBytes because I think that's what the original returns? Only problem is I forgot the write code depends on that value to be 0x13 most of the time (not sure why) and that's probably why it's off by one now.

**Comment by nesrak1** [comment]
Let me know if the changes I made a while ago fix the issues you guys brought up. It's working fine on my end but I want to make sure you guys don't have any problems before I make a nuget release.

**Comment by rashime** [comment]
The first issue I had which I thought was related (the 0x13 value) was fixed in the update.

While modifying a different file in the bundle, I did run into this issue though (the replacement character being added when extracting/modifying a script value).

In the bundle I am messing with, the asset is stored as TextAsset and m_Script is marked as a string, but it is not actually a UTF-8 string (it is a .NET binary serialization). Because of that, when Encoding.UTF8.GetString is called in AssetTypeTemplateField the data gets corrupted with the replacement character.

I worked around it in the project I was working on by modifying AssetTypeTemplateField to retrieve the raw bytes instead of a string, then modified AssetTypeValue to store the raw value before processing as a string ([example](https://github.com/lo-translate/lo-patcher/blob/master/.docs/extract-string-as-bytes.patch)).  I also had to write the asset to a replacer like you outlined above rather than using WriteToByteArray for the same reason.

I am not sure if this is an abnormal thing being done by the bundle creator or if it is common.  I also didn't think my solution to the problem was good as a general solution (just the quickest I could figure out) so I didn't look into submitting a pull request.

**Comment by nesrak1** [comment]
UABE's AssetsTools just used char* which works well in c++ but not so much here.
The method you used is a good option. I could also leave the string in something like latin-1 which should encode/decode the same and then do utf8 conversion only if needed. If you have any other suggestions I'm open.

> I am not sure if this is an abnormal thing being done by the bundle creator or if it is common.

TextAssets have support for binary files so it's totally fine for them to be used like that. As far as I know though, it's the only time binary data is ever in a string so this is sort of an exception.

**Comment by rashime** [comment]
I don't have any ideas on the encoding unfortunately and don't know whether the latin-1 idea would work.  Happy to test or provide the bundle I am modifying if wanted.

The main problem I have with the way I accomplished it, is as a library consumer you'd have no way of knowing what GetRawValue will return.

If I were to try implementing that again I'd definitely change it to be stored and retrieved as byte[]. My initial thought was add a second Set(byte[]) and AsBytes() but that would probably make things confusing for people since there is the separate AssetTypeByteArray type and AsByteArray method.

I am not sure how that would work with non-string value types though. Unless AssetTypeTemplateField was adjusted for all types (which seems like overkill) the 'raw' value would be empty for non-string types. Thinking more on it, the change would also require modification to AssetWriter to use the 'raw' value instead of the string so WriteToByteArray can be used after updating the value with Set.

**Comment by nesrak1** [comment]
I think I'm just going to go with keeping strings as byte[] and only convert to a utf8 string when .Set/AsString() is called. As for the function to get raw bytes, maybe .AsRaw() would be less confusing than .AsBytes()?

**Comment by rashime** [comment]
Since it will only be set for strings, what about .AsRawString()? (or .AsStringBytes())  Might make it more clear to users when the function can be used.

**Comment by nesrak1** [comment]
Let me know if that latest commit works for you

**Comment by rashime** [comment]
The latest commit works for me.  Retrieving the non-UTF8 script with AsStringBytes works and after updating the bytes with Set(), baseField.WriteToByteArray() can create a replacer buffer that works.

**Comment by nesrak1** [comment]
Closing this unless @remixer-dec has any other problems
