### ISSUE TITLE
Is there has anyway to replace a texture2d resource in asset file?

### ISSUE THREAD

**Issue by HxBreak** [nesrak1/AssetsTools.NET#38]

**Comment by nesrak1** [comment]
I don't know what you mean by "resource". Do you mean replacing the image data in a texture2d? If so just use the texture decoding/encoding from UABEA. It uses native libraries though since there aren't any good managed libraries to do it.
Then for replacing the asset, look at the readme on using AssetsReplacers.

**Comment by HxBreak** [comment]
Yes, It 's image data, But image data looks like saved in sharedassetsxx.assets.resS, Is it still can be store in sharedassetxx.assets?

**Comment by nesrak1** [comment]
You can choose to store it in the `image data` field in .assets by zeroing out the `m_StreamData` fields, or you can add new data to .resS and change the `m_StreamData` fields to the offset and size in the resS file.

Side note, one of the reasons I think UABE doesn't edit the resS is because in some cases the texture can be larger than the original, and since everything is offsets, it would have to copy the data to the end of the file anyway.

**Comment by HxBreak** [comment]
It 's looks a nice advice, I will make a try.
