### ISSUE TITLE
Help !!!

### ISSUE THREAD

**Issue by usnail** [nesrak1/AssetsTools.NET#6]
the game engine update to  unity 2018.
I can not  use c/c++.
please update!!!
Thanks  very much.

**Comment by usnail** [comment]
Thanks for your answer.
I will try it again.
Excuse me for my poor English.

**Comment by usnail** [comment]
Thank you again. I've been able to open file successfully.
But I can't use a replacement file。

**Comment by nesrak1** [comment]
What are you trying to do

**Comment by usnail** [comment]
I've been try replace file in Asset.
in your project ,already  have AssetsTools.NETTester.
I used UABE export  raw and modify AssetsTools.NETTester code.
I opend the save file , the file name and pathid is error

**Comment by nesrak1** [comment]
To modify an asset you would get the absolute position and curFileSize from an asset's infoex and use a stream or binaryreader to read the bytes. You can modify the bytes and create an asset replacer from memory using the bytes you modified. Then use save with the replacers list.
Also there may be a bug in the save code which hasn't made public yet due to some other issues. If the created assets file errors on open, try replacing the AssetsFile.Write method with this method here: https://github.com/nesrak1/HKWorldEdit/blob/master/Assets/Editor/AssetBundler/Extensions.cs#L127

**Comment by nesrak1** [comment]
The latest commit should have fixed this write bug.

**Comment by usnail** [comment]
Thanks again.
some assets file errors on read.
`AssetCount = reader.ReadUInt32();
            reader.Align();
            AssetTablePos = Convert.ToUInt32(reader.BaseStream.Position);
            
            reader.BaseStream.Position += AssetFileInfo.GetSize(header.format) * AssetCount;
            if (header.format > 0x0B)
            {
                preloadTable = new PreloadList();
                preloadTable.Read(reader.Position, reader, header.format, reader.bigEndian);
            }`
the position of set is more than file size.

**Comment by nesrak1** [comment]
Send me an assets file if you can so I can debug

**Comment by nesrak1** [comment]
I opened these with uabe and uabe.net and they both opened fine. Also make sure you have exported the class database uncompressed.
From the readme I'm going to add later:

In UABE, go to `Options > Edit Type Package`. Open classdata.tpk in the same folder as UABE. Find the Unity version you need and click "Export". Then close the window and go to `Options > Edit Type Database`. Open the file you exported, uncheck `Compress the file (LZMA)`, click OK, then OK again.

**Comment by usnail** [comment]
Oh,sorry.
I have re-exported a class database  file.
uabe.net only one file opend failed. the file:https://mega.nz/#!n6p3xQbS!0jZp4-NRuPAc_n8Psc_5iSzEzmae2ekM5qWl6tu4pho
I removed all replacers  and only opend and save use AssetsTools.NETTester. the file of created still error.

**Comment by usnail** [comment]
thanks.
all file opened fine. if I remove all replacers and only open if and save used by AssetsTools.NETTester. the file no errors.then I modify the bytes and create an asset replacer from memory using the bytes I modified. the file has errors start by the modify position.
Is there something wrong with my operation?

**Comment by nesrak1** [comment]
Can you send the modified assets file / code you are using to modify bytes?

**Comment by usnail** [comment]
```C#
 AssetsReplacer assetsReplacer1 = new AssetsReplacerFromFile(0, 3146, 0x1C, 0, new FileStream("3146.dat", FileMode.Open), 0, (ulong)new FileInfo("3146.dat").Length);
```
I edit the file path  and the file size use code read.
modify  file is here:https://mega.nz/#!n6p3xQbS!0jZp4-NRuPAc_n8Psc_5iSzEzmae2ekM5qWl6tu4pho
you should be already download.


modify bytes is here:https://mega.nz/#!TzIQ0SAD!zcexwz-bSqtybjCDUmshYi4u2Cs0Zz6P1j_ds-cF1PU

**Comment by usnail** [comment]
By the way.
Is there any way to create bytes from files? eg：png  mp3
I used uabe modifyand export  .

**Comment by nesrak1** [comment]
Nope, importing these assets back in is not supported. However, you can always import it into unity, build the project, then "export raw" out of the project's assets and "import raw" it back into the game with uabe. I'll look at your modified bytes tomorrow but from a glance, I don't see anything wrong with your code yet.

**Comment by usnail** [comment]
thanks

**Comment by nesrak1** [comment]
I forgot that UABE has a plugin for texture importing so you can click on texture -> plugins -> edit -> load and remember to file -> save, however I'm not sure you can automate that.
As for the write bug, it was caused by the other assets not moving their offsets up which I believe the original assetstools solved by pushing it to the end of the file, so I'll try to see if I can replicate what it does. A commit should be coming soon that fixes the write bug with the current write method.

**Comment by nesrak1** [comment]
Sorry about the wait. See if you can write without corruption.

**Comment by usnail** [comment]
Thanks.I will try again.
